name: Build Mac
run-name: Build Mac
# on:
#   push:
#     tags:
#       - "**"
on: [push]
jobs:
  Build-Windows:
    runs-on: macos-latest
    steps:
      # Use Python 3.12.4
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"
      - run: git clone https://github.com/mak448a/QTCord/ --depth=1
      - run: cd QTCord/helper_scripts && pip install -r requirements.txt && pip install pyinstaller && python3 package_mac.py
      - uses: actions/upload-artifact@v4
        with:
            name: "QTCord-Mac"
            path: "QTCord/src/dist/QTCord"
