name: Build macOS
run-name: Build macOS
on:
  push:
    tags:
      - "**"

jobs:
  Build-macOS:
    runs-on: macos-latest
    steps:
      # Use Python 3.12.4
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"
      - run: git clone https://github.com/mak448a/Qtcord/ --depth=1
      - run: pip install -r requirements.txt && pip install pyinstaller && python3 helper_scripts/package_macos.py
      - uses: actions/upload-artifact@v4
        with:
          name: "Qtcord-macOS"
          path: "src/dist/Qtcord"
